# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eskamb_App', '0006_usuariomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Eskamb_App.Usuario')),
                ('NomeFantasia', models.CharField(max_length=100)),
                ('razaoSocial', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('porte', models.CharField(max_length=2)),
                ('ramoAtividade', models.CharField(max_length=2)),
            ],
        ),
    ]
