# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eskamb_App', '0007_pessoajuridica'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Eskamb_App.Usuario')),
                ('nomeCompleto', models.CharField(max_length=100)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eskamb_App.Formacao')),
            ],
        ),
    ]
